title: Joel Smith # your name (or website title) here
logo: "/images/me.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of professional data experience split between manufacturing and trucking. Experience in engineering as well. Obtained a Master's Degree in Biostatistics in 2019.
  <br><br>
  Currently working as part the Business Intelligence team at Holland as a Data Scientist. I'm in the Advanced Analytics group, working with Operations, Sales, and Pricing departments.
  <br><br>
  <a href="https://www.linkedin.com/in/joel-p-smith/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
